#theme: jekyll-theme-cayman
title: Living Labs for Academic Search (LiLAS) 
description: Workshop at CLEF 2020, Thessaloniki, Greece, 22-25 September 2020

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
